export const BUSINESS = {
  name: 'Elite Laser Kiosk',
  shortName: 'Elite Laser',
  monogram: 'EL',
  tagline: 'Precision laser. Permanent results.',
  founded: '2022',
  phone: '416-671-6716',
  instagram: 'elitelaserkiosk',
  instagramUrl: 'https://instagram.com/elitelaserkiosk',
  email: 'book@elitelaserkiosk.ca',
  address: {
    street: '14120 Danby Rd',
    city: 'Norval',
    province: 'ON',
    postal: 'L0P 1K0',
    full: '14120 Danby Rd, Norval, ON L0P 1K0',
    neighborhood: 'Norval',
  },
  hours: [
    { day: 'Monday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Tuesday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Wednesday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Thursday', hours: '10:00 AM – 8:00 PM' },
    { day: 'Friday', hours: '10:00 AM – 8:00 PM' },
    { day: 'Saturday', hours: '9:00 AM – 6:00 PM' },
    { day: 'Sunday', hours: '10:00 AM – 5:00 PM' },
  ],
  sessionsRequired: '6–8',
  technologyUsed: 'Diode 808nm Laser',
} as const
