/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationRouteImport } from './routes/location'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesUpperLipRouteImport } from './routes/services.upper-lip'
import { Route as ServicesUnderarmsRouteImport } from './routes/services.underarms'
import { Route as ServicesSideburnsRouteImport } from './routes/services.sideburns'
import { Route as ServicesJawlineNeckRouteImport } from './routes/services.jawline-neck'
import { Route as ServicesHalfLegsRouteImport } from './routes/services.half-legs'
import { Route as ServicesHalfArmsRouteImport } from './routes/services.half-arms'
import { Route as ServicesFullLegsRouteImport } from './routes/services.full-legs'
import { Route as ServicesFullFaceRouteImport } from './routes/services.full-face'
import { Route as ServicesFullBodyRouteImport } from './routes/services.full-body'
import { Route as ServicesFullArmsRouteImport } from './routes/services.full-arms'
import { Route as ServicesChinRouteImport } from './routes/services.chin'
import { Route as ServicesChestStomachRouteImport } from './routes/services.chest-stomach'
import { Route as ServicesBrowDefineRouteImport } from './routes/services.brow-define'
import { Route as ServicesBrazilianRouteImport } from './routes/services.brazilian'
import { Route as ServicesBikiniLineRouteImport } from './routes/services.bikini-line'
import { Route as ServicesBackRouteImport } from './routes/services.back'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUpperLipRoute = ServicesUpperLipRouteImport.update({
  id: '/upper-lip',
  path: '/upper-lip',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUnderarmsRoute = ServicesUnderarmsRouteImport.update({
  id: '/underarms',
  path: '/underarms',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSideburnsRoute = ServicesSideburnsRouteImport.update({
  id: '/sideburns',
  path: '/sideburns',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesJawlineNeckRoute = ServicesJawlineNeckRouteImport.update({
  id: '/jawline-neck',
  path: '/jawline-neck',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHalfLegsRoute = ServicesHalfLegsRouteImport.update({
  id: '/half-legs',
  path: '/half-legs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHalfArmsRoute = ServicesHalfArmsRouteImport.update({
  id: '/half-arms',
  path: '/half-arms',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullLegsRoute = ServicesFullLegsRouteImport.update({
  id: '/full-legs',
  path: '/full-legs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullFaceRoute = ServicesFullFaceRouteImport.update({
  id: '/full-face',
  path: '/full-face',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullBodyRoute = ServicesFullBodyRouteImport.update({
  id: '/full-body',
  path: '/full-body',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullArmsRoute = ServicesFullArmsRouteImport.update({
  id: '/full-arms',
  path: '/full-arms',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesChinRoute = ServicesChinRouteImport.update({
  id: '/chin',
  path: '/chin',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesChestStomachRoute = ServicesChestStomachRouteImport.update({
  id: '/chest-stomach',
  path: '/chest-stomach',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBrowDefineRoute = ServicesBrowDefineRouteImport.update({
  id: '/brow-define',
  path: '/brow-define',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBrazilianRoute = ServicesBrazilianRouteImport.update({
  id: '/brazilian',
  path: '/brazilian',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBikiniLineRoute = ServicesBikiniLineRouteImport.update({
  id: '/bikini-line',
  path: '/bikini-line',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBackRoute = ServicesBackRouteImport.update({
  id: '/back',
  path: '/back',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/back': typeof ServicesBackRoute
  '/services/bikini-line': typeof ServicesBikiniLineRoute
  '/services/brazilian': typeof ServicesBrazilianRoute
  '/services/brow-define': typeof ServicesBrowDefineRoute
  '/services/chest-stomach': typeof ServicesChestStomachRoute
  '/services/chin': typeof ServicesChinRoute
  '/services/full-arms': typeof ServicesFullArmsRoute
  '/services/full-body': typeof ServicesFullBodyRoute
  '/services/full-face': typeof ServicesFullFaceRoute
  '/services/full-legs': typeof ServicesFullLegsRoute
  '/services/half-arms': typeof ServicesHalfArmsRoute
  '/services/half-legs': typeof ServicesHalfLegsRoute
  '/services/jawline-neck': typeof ServicesJawlineNeckRoute
  '/services/sideburns': typeof ServicesSideburnsRoute
  '/services/underarms': typeof ServicesUnderarmsRoute
  '/services/upper-lip': typeof ServicesUpperLipRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services/back': typeof ServicesBackRoute
  '/services/bikini-line': typeof ServicesBikiniLineRoute
  '/services/brazilian': typeof ServicesBrazilianRoute
  '/services/brow-define': typeof ServicesBrowDefineRoute
  '/services/chest-stomach': typeof ServicesChestStomachRoute
  '/services/chin': typeof ServicesChinRoute
  '/services/full-arms': typeof ServicesFullArmsRoute
  '/services/full-body': typeof ServicesFullBodyRoute
  '/services/full-face': typeof ServicesFullFaceRoute
  '/services/full-legs': typeof ServicesFullLegsRoute
  '/services/half-arms': typeof ServicesHalfArmsRoute
  '/services/half-legs': typeof ServicesHalfLegsRoute
  '/services/jawline-neck': typeof ServicesJawlineNeckRoute
  '/services/sideburns': typeof ServicesSideburnsRoute
  '/services/underarms': typeof ServicesUnderarmsRoute
  '/services/upper-lip': typeof ServicesUpperLipRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/back': typeof ServicesBackRoute
  '/services/bikini-line': typeof ServicesBikiniLineRoute
  '/services/brazilian': typeof ServicesBrazilianRoute
  '/services/brow-define': typeof ServicesBrowDefineRoute
  '/services/chest-stomach': typeof ServicesChestStomachRoute
  '/services/chin': typeof ServicesChinRoute
  '/services/full-arms': typeof ServicesFullArmsRoute
  '/services/full-body': typeof ServicesFullBodyRoute
  '/services/full-face': typeof ServicesFullFaceRoute
  '/services/full-legs': typeof ServicesFullLegsRoute
  '/services/half-arms': typeof ServicesHalfArmsRoute
  '/services/half-legs': typeof ServicesHalfLegsRoute
  '/services/jawline-neck': typeof ServicesJawlineNeckRoute
  '/services/sideburns': typeof ServicesSideburnsRoute
  '/services/underarms': typeof ServicesUnderarmsRoute
  '/services/upper-lip': typeof ServicesUpperLipRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/back'
    | '/services/bikini-line'
    | '/services/brazilian'
    | '/services/brow-define'
    | '/services/chest-stomach'
    | '/services/chin'
    | '/services/full-arms'
    | '/services/full-body'
    | '/services/full-face'
    | '/services/full-legs'
    | '/services/half-arms'
    | '/services/half-legs'
    | '/services/jawline-neck'
    | '/services/sideburns'
    | '/services/underarms'
    | '/services/upper-lip'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services/back'
    | '/services/bikini-line'
    | '/services/brazilian'
    | '/services/brow-define'
    | '/services/chest-stomach'
    | '/services/chin'
    | '/services/full-arms'
    | '/services/full-body'
    | '/services/full-face'
    | '/services/full-legs'
    | '/services/half-arms'
    | '/services/half-legs'
    | '/services/jawline-neck'
    | '/services/sideburns'
    | '/services/underarms'
    | '/services/upper-lip'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/back'
    | '/services/bikini-line'
    | '/services/brazilian'
    | '/services/brow-define'
    | '/services/chest-stomach'
    | '/services/chin'
    | '/services/full-arms'
    | '/services/full-body'
    | '/services/full-face'
    | '/services/full-legs'
    | '/services/half-arms'
    | '/services/half-legs'
    | '/services/jawline-neck'
    | '/services/sideburns'
    | '/services/underarms'
    | '/services/upper-lip'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  LocationRoute: typeof LocationRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/upper-lip': {
      id: '/services/upper-lip'
      path: '/upper-lip'
      fullPath: '/services/upper-lip'
      preLoaderRoute: typeof ServicesUpperLipRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/underarms': {
      id: '/services/underarms'
      path: '/underarms'
      fullPath: '/services/underarms'
      preLoaderRoute: typeof ServicesUnderarmsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sideburns': {
      id: '/services/sideburns'
      path: '/sideburns'
      fullPath: '/services/sideburns'
      preLoaderRoute: typeof ServicesSideburnsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/jawline-neck': {
      id: '/services/jawline-neck'
      path: '/jawline-neck'
      fullPath: '/services/jawline-neck'
      preLoaderRoute: typeof ServicesJawlineNeckRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/half-legs': {
      id: '/services/half-legs'
      path: '/half-legs'
      fullPath: '/services/half-legs'
      preLoaderRoute: typeof ServicesHalfLegsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/half-arms': {
      id: '/services/half-arms'
      path: '/half-arms'
      fullPath: '/services/half-arms'
      preLoaderRoute: typeof ServicesHalfArmsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-legs': {
      id: '/services/full-legs'
      path: '/full-legs'
      fullPath: '/services/full-legs'
      preLoaderRoute: typeof ServicesFullLegsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-face': {
      id: '/services/full-face'
      path: '/full-face'
      fullPath: '/services/full-face'
      preLoaderRoute: typeof ServicesFullFaceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-body': {
      id: '/services/full-body'
      path: '/full-body'
      fullPath: '/services/full-body'
      preLoaderRoute: typeof ServicesFullBodyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-arms': {
      id: '/services/full-arms'
      path: '/full-arms'
      fullPath: '/services/full-arms'
      preLoaderRoute: typeof ServicesFullArmsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/chin': {
      id: '/services/chin'
      path: '/chin'
      fullPath: '/services/chin'
      preLoaderRoute: typeof ServicesChinRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/chest-stomach': {
      id: '/services/chest-stomach'
      path: '/chest-stomach'
      fullPath: '/services/chest-stomach'
      preLoaderRoute: typeof ServicesChestStomachRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/brow-define': {
      id: '/services/brow-define'
      path: '/brow-define'
      fullPath: '/services/brow-define'
      preLoaderRoute: typeof ServicesBrowDefineRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/brazilian': {
      id: '/services/brazilian'
      path: '/brazilian'
      fullPath: '/services/brazilian'
      preLoaderRoute: typeof ServicesBrazilianRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/bikini-line': {
      id: '/services/bikini-line'
      path: '/bikini-line'
      fullPath: '/services/bikini-line'
      preLoaderRoute: typeof ServicesBikiniLineRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/back': {
      id: '/services/back'
      path: '/back'
      fullPath: '/services/back'
      preLoaderRoute: typeof ServicesBackRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesBackRoute: typeof ServicesBackRoute
  ServicesBikiniLineRoute: typeof ServicesBikiniLineRoute
  ServicesBrazilianRoute: typeof ServicesBrazilianRoute
  ServicesBrowDefineRoute: typeof ServicesBrowDefineRoute
  ServicesChestStomachRoute: typeof ServicesChestStomachRoute
  ServicesChinRoute: typeof ServicesChinRoute
  ServicesFullArmsRoute: typeof ServicesFullArmsRoute
  ServicesFullBodyRoute: typeof ServicesFullBodyRoute
  ServicesFullFaceRoute: typeof ServicesFullFaceRoute
  ServicesFullLegsRoute: typeof ServicesFullLegsRoute
  ServicesHalfArmsRoute: typeof ServicesHalfArmsRoute
  ServicesHalfLegsRoute: typeof ServicesHalfLegsRoute
  ServicesJawlineNeckRoute: typeof ServicesJawlineNeckRoute
  ServicesSideburnsRoute: typeof ServicesSideburnsRoute
  ServicesUnderarmsRoute: typeof ServicesUnderarmsRoute
  ServicesUpperLipRoute: typeof ServicesUpperLipRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBackRoute: ServicesBackRoute,
  ServicesBikiniLineRoute: ServicesBikiniLineRoute,
  ServicesBrazilianRoute: ServicesBrazilianRoute,
  ServicesBrowDefineRoute: ServicesBrowDefineRoute,
  ServicesChestStomachRoute: ServicesChestStomachRoute,
  ServicesChinRoute: ServicesChinRoute,
  ServicesFullArmsRoute: ServicesFullArmsRoute,
  ServicesFullBodyRoute: ServicesFullBodyRoute,
  ServicesFullFaceRoute: ServicesFullFaceRoute,
  ServicesFullLegsRoute: ServicesFullLegsRoute,
  ServicesHalfArmsRoute: ServicesHalfArmsRoute,
  ServicesHalfLegsRoute: ServicesHalfLegsRoute,
  ServicesJawlineNeckRoute: ServicesJawlineNeckRoute,
  ServicesSideburnsRoute: ServicesSideburnsRoute,
  ServicesUnderarmsRoute: ServicesUnderarmsRoute,
  ServicesUpperLipRoute: ServicesUpperLipRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  LocationRoute: LocationRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
